USE [master]
GO

/****** Object:  Database [WorldCupFoodie]    Script Date: 12/1/2022 9:18:18 PM ******/
 DROP DATABASE IF EXISTS [WorldCupFoodie]
GO

/****** Object:  Database [WorldCupFoodie]    Script Date: 12/1/2022 9:18:18 PM ******/
CREATE DATABASE [WorldCupFoodie]

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [WorldCupFoodie].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [WorldCupFoodie] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [WorldCupFoodie] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [WorldCupFoodie] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [WorldCupFoodie] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [WorldCupFoodie] SET ARITHABORT OFF 
GO

ALTER DATABASE [WorldCupFoodie] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [WorldCupFoodie] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [WorldCupFoodie] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [WorldCupFoodie] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [WorldCupFoodie] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [WorldCupFoodie] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [WorldCupFoodie] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [WorldCupFoodie] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [WorldCupFoodie] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [WorldCupFoodie] SET  DISABLE_BROKER 
GO

ALTER DATABASE [WorldCupFoodie] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [WorldCupFoodie] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [WorldCupFoodie] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [WorldCupFoodie] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [WorldCupFoodie] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [WorldCupFoodie] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [WorldCupFoodie] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [WorldCupFoodie] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [WorldCupFoodie] SET  MULTI_USER 
GO

ALTER DATABASE [WorldCupFoodie] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [WorldCupFoodie] SET DB_CHAINING OFF 
GO

ALTER DATABASE [WorldCupFoodie] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [WorldCupFoodie] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [WorldCupFoodie] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [WorldCupFoodie] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [WorldCupFoodie] SET QUERY_STORE = OFF
GO

ALTER DATABASE [WorldCupFoodie] SET  READ_WRITE 
GO

USE [WorldCupFoodie]

CREATE TABLE [dbo].[Matches](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Team1] [nvarchar](30) NULL,
	[Team2] [nvarchar](30) NULL,
	[MatchDate] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[Dishes](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[MatchId] [int] NULL,
	[Dish] [varchar](20) NULL,
	[Description] [text] NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[Dishes]  WITH CHECK ADD FOREIGN KEY([MatchId])
REFERENCES [dbo].[Matches] ([Id])
GO

